services:
  db:
    image: mariadb:11.4
    container_name: joe_db_v2_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "9012:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: joe_backend_v2_dev
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: ${APP_URL}

      DB_CONNECTION: mysql
      DB_HOST: db              # service name
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9011:80"

  composer:
    image: composer:2
    container_name: joe_composer_v2_dev
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["composer", "install", "--no-interaction"]

  frontend:
    image: node:22
    container_name: joe_frontend_v2_dev
    working_dir: /app
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "9010:5173"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: joe_phpmyadmin_v2_dev
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "9013:80"
