<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SwcFacilityType extends Model
{
    protected $fillable = [
        'uid',
        'name',
        'class_uid',
        'class_name',
        'size',
        'sensors',
        'weight_tonnes',
        'volume_m3',
        'volume_capacity_m3',
        'max_passengers',
        'flat_count',
        'job_count',
        'size_x',
        'size_y',
        'hull',
        'shield',
        'ionic_capacity',
        'energy',
        'can_load_materials',
        'can_earn_income',
        'medical_rooms',
        'has_hangar_bay',
        'has_docking_bay',
        'can_recycle',
        'can_produce',
        'can_mine',
        'can_refine_alazhi',
        'can_farm_alazhi',
        'can_research',
        'production_modifier',
        'recommended_workers',
        'recycling_xp',
        'generic_slots',
        'weapons',
        'materials',
        'length',
        'width',
        'height',
        'description',
        'price_credits',
        'images',
        'image_url',
        'icon_url',
        'payload',
        'last_pulled_at',
    ];

    protected $casts = [
        'sensors' => 'integer',
        'weight_tonnes' => 'decimal:2',
        'volume_m3' => 'decimal:2',
        'volume_capacity_m3' => 'decimal:2',
        'max_passengers' => 'integer',
        'flat_count' => 'integer',
        'job_count' => 'integer',
        'size_x' => 'integer',
        'size_y' => 'integer',
        'hull' => 'integer',
        'shield' => 'integer',
        'ionic_capacity' => 'integer',
        'energy' => 'integer',
        'can_load_materials' => 'boolean',
        'can_earn_income' => 'boolean',
        'medical_rooms' => 'integer',
        'has_hangar_bay' => 'boolean',
        'has_docking_bay' => 'boolean',
        'can_recycle' => 'boolean',
        'can_produce' => 'boolean',
        'can_mine' => 'boolean',
        'can_refine_alazhi' => 'boolean',
        'can_farm_alazhi' => 'boolean',
        'can_research' => 'boolean',
        'production_modifier' => 'integer',
        'recommended_workers' => 'integer',
        'recycling_xp' => 'integer',
        'generic_slots' => 'integer',
        'weapons' => 'array',
        'materials' => 'array',
        'length' => 'decimal:2',
        'width' => 'decimal:2',
        'height' => 'decimal:2',
        'images' => 'array',
        'payload' => 'array',
        'last_pulled_at' => 'datetime',
    ];
}
