FROM php:8.3-apache

RUN apt-get update && apt-get install -y \
    git unzip libzip-dev libonig-dev libicu-dev \
 && docker-php-ext-install pdo pdo_mysql mbstring zip intl \
 && a2enmod rewrite

WORKDIR /var/www/html

COPY . /var/www/html

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN composer install --no-dev --optimize-autoloader

RUN php artisan config:cache || true \
 && php artisan route:cache || true

EXPOSE 80
